[package]
name = "fifteen_min"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["map_gui/native", "widgetry/native-backend"]
wasm = ["getrandom/js", "map_gui/wasm", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
contour = { workspace = true }
geojson = { workspace = true }
geom = { path = "../../geom" }
getrandom = { version = "0.2.3", optional = true }
log = "0.4"
map_gui = { path = "../../map_gui" }
map_model = { path = "../../map_model" }
structopt = { workspace = true }
synthpop = { path = "../../synthpop" }  # TODO Remove
wasm-bindgen = { version = "0.2.70", optional = true }
widgetry = { path = "../../widgetry" }
