[package]
name = "map_editor"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["widgetry/native-backend"]
wasm = ["getrandom/js", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
fs-err = { workspace = true }
geom = { workspace = true }
getrandom = { workspace = true, optional = true }
log = { workspace = true }
raw_map = { path = "../../raw_map" }
serde = { workspace = true }
osm2streets = { git = "https://github.com/a-b-street/osm2streets" }
structopt = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
widgetry = { path = "../../widgetry" }
