[package]
name = "game"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

# TODO Can't toggle based on target_arch. https://github.com/rust-lang/cargo/issues/2524
# cargo web start --target wasm32-unknown-unknown --no-default-features --features wasm
[features]
default = ["built", "ezgui/glium-backend"]
wasm = ["ezgui/wasm-backend"]

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
built = { version = "0.4.0", optional = true, features=["chrono"] }
chrono = "0.4.10"
downcast-rs = "1.1.1"
ezgui = { path = "../ezgui", default-features=false }
geom = { path = "../geom" }
instant = "0.1.2"
kml = { path = "../kml" }
maplit = "1.0.2"
map_model = { path = "../map_model" }
rand = "0.7.0"
rand_xorshift = "0.2.0"
serde = "1.0.98"
serde_derive = "1.0.98"
sim = { path = "../sim" }

[build-dependencies]
built = "0.3.2"
walkdir = "2.2.7"
