[package]
name = "game"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

# TODO Can't toggle based on target_arch. https://github.com/rust-lang/cargo/issues/2524
# cargo web start --target wasm32-unknown-unknown --no-default-features --features wasm
[features]
default = ["built", "clipboard", "ezgui/glium-backend", "reqwest", "webbrowser"]
wasm = ["ezgui/wasm-backend"]

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
built = { version = "0.4.2", optional = true, features=["chrono"] }
chrono = "0.4.10"
clipboard = { version = "0.5.0", optional = true }
colorous = "1.0.1"
downcast-rs = "1.1.1"
ezgui = { path = "../ezgui", default-features=false }
geom = { path = "../geom" }
instant = "0.1.2"
kml = { path = "../kml" }
lttb = "0.2.0"
maplit = "1.0.2"
map_model = { path = "../map_model" }
marching-squares = "0.1.1"
petgraph = "0.5.0"
petname = "1.0.12"
rand = "0.7.0"
rand_xorshift = "0.2.0"
reqwest = { version = "0.10.6", optional = true, default-features=false, features=["blocking", "rustls-tls"] }
serde = "1.0.110"
svg_face = "0.1.2"
sim = { path = "../sim" }
webbrowser = { version = "0.5.2", optional = true }
xmltree = "0.10.0"

[build-dependencies]
built = "0.4.2"
walkdir = "2.2.7"
