[package]
name = "santa"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["map_gui/native", "widgetry/native-backend"]
wasm = ["map_gui/wasm", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
kml = { path = "../kml" }
log = "0.4.11"
map_gui = { path = "../map_gui" }
map_model = { path = "../map_model" }
rand = "0.7.0"
rand_xorshift = "0.2.0"
rodio = { version = "0.13.0", default-features = false, features = ["vorbis"] }
serde = "1.0.116"
wasm-bindgen = { version = "0.2.68", optional = true }
widgetry = { path = "../widgetry" }
