[package]
name = "widgetry"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
native-backend = ["clipboard", "glutin", "tokio", "usvg/text"]
wasm-backend = ["instant/wasm-bindgen", "js-sys", "usvg/text", "wasm-bindgen", "wasm-bindgen-futures", "wasm-streams", "web-sys"]

[dependencies]
aabb-quadtree = "0.1.0"
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
# backtrace = "0.3.40"
clipboard = { version = "0.5.0", optional = true }
colorous = "1.0.3"
downcast-rs = "1.2.0"
flate2 = "1.0.20"
fs-err = { workspace = true }
futures = { version = "0.3.12" }
futures-channel = { version = "0.3.12"}
geojson = { workspace = true }
geom = { path = "../geom" }
glow = "0.11.2"
glutin = { git = "https://github.com/rust-windowing/glutin", optional = true }
htmlescape = "0.3.1"
image = { version = "0.24.3", default-features = false, features=["gif", "png"] }
instant = { workspace = true }
js-sys = { version = "0.3.47", optional = true }
log = { workspace = true }
lru = "0.7.1"
lyon = "1.0.0"
serde = { workspace = true }
serde_json = { workspace = true }
taffy = "0.2.0"
tokio = { version ="1.19.2", features=["full"], optional = true }
ttf-parser = "0.15.0"
usvg = { version = "0.22.0", default-features=false, features=["text"] }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { version = "0.4.20", optional = true }
wasm-streams = { version = "0.2.0", optional = true }
webbrowser = "0.8.6"
winit = "0.27.0"

[dependencies.web-sys]
workspace = true
optional = true
# TODO Some of these may only be needed in map_gui. It's hard to detangle.
features = [
  "Headers",
  "History",
  "ReadableStream",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
