[package]
name = "widgetry"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[features]
native-backend = ["glow", "glutin", "usvg/system-fonts", "usvg/text"]
wasm-backend = ["glow/web-sys", "instant/wasm-bindgen", "usvg/text", "wasm-bindgen", "web-sys", "winit/web-sys"]

[dependencies]
abstutil = { path = "../abstutil" }
anyhow = "1.0.37"
# backtrace = "0.3.40"
downcast-rs = "1.2.0"
geojson = "0.21.0"
geom = { path = "../geom" }
glow = { version = "0.7.1", optional = true, default-features=false }
glutin = { version = "0.26.0", optional = true }
htmlescape = "0.3.1"
image = { version = "0.23.12", default-features = false, features=["png"] }
instant = "0.1.7"
log = "0.4.11"
lru = "0.6.3"
lyon = "0.16.2"
serde = "1.0.116"
serde_json = "1.0.61"
stretch = "0.3.2"
ttf-parser = "0.9.0"
usvg = { version = "0.13.0", default-features=false }
wasm-bindgen = { version = "0.2.68", optional = true }
web-sys = { version = "0.3.45", optional = true }
winit = "0.24.0"
