[package]
name = "widgetry"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
native-backend = ["glutin", "tokio", "usvg/text"]
wasm-backend = ["instant/wasm-bindgen", "js-sys", "usvg/text", "wasm-bindgen", "wasm-bindgen-futures", "wasm-streams", "web-sys"]

[dependencies]
aabb-quadtree = "0.1.0"
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
# backtrace = "0.3.40"
downcast-rs = "1.2.0"
flate2 = "1.0.20"
fs-err = "2.6.0"
futures = { version = "0.3.12" }
futures-channel = { version = "0.3.12"}
geojson = { version = "0.22.2", features = ["geo-types"] }
geom = { path = "../geom" }
glow = "0.11.2"
glutin = { version = "0.28.0", optional = true }
htmlescape = "0.3.1"
image = { version = "0.23.12", default-features = false, features=["png"] }
instant = "0.1.7"
js-sys = { version = "0.3.47", optional = true }
log = "0.4.14"
lru = "0.6.4"
# Don't upgrade until a crash with opening lane info panels is fixed
lyon = "0.16.2"
serde = "1.0.123"
serde_json = "1.0.61"
stretch = "0.3.2"
tokio = { version ="1.1.1", features=["full"], optional = true }
ttf-parser = "0.15.0"
usvg = { version = "0.22.0", default-features=false, features=["text"] }
wasm-bindgen = { version = "0.2.70", optional = true }
wasm-bindgen-futures = { version = "0.4.20", optional = true }
wasm-streams = { version = "0.2.0", optional = true }
webbrowser = "0.5.5"
winit = "0.26.1"

[dependencies.web-sys]
version = "0.3.47"
optional = true
# TODO Some of these may only be needed in map_gui. It's hard to detangle.
features = [
  "Headers",
  "History",
  "ReadableStream",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
