[package]
name = "game"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"
description = "A traffic simulation game based on OpenStreetMap"
repository = "https://github.com/a-b-street/abstreet"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["map_gui/native", "widgetry/native-backend"]
wasm = ["getrandom/js", "map_gui/wasm", "wasm-bindgen", "widgetry/wasm-backend"]

[dependencies]
abstio = { path = "../../abstio" }
abstutil = { path = "../../abstutil" }
anyhow = { workspace = true }
blockfinding = { path = "../../blockfinding" }
collisions = { path = "../../collisions" }
colorous = { workspace = true }
contour = { workspace = true }
csv = { workspace = true }
downcast-rs = "1.2.0"
enumset = "1.0.3"
fs-err = { workspace = true }
futures-channel = { version = "0.3.12"}
geo = { workspace = true }
geojson = { workspace = true }
geom = { path = "../../geom" }
getrandom = { workspace = true, optional = true }
instant = { workspace = true }
kml = { path = "../../kml" }
lazy_static = "1.4.0"
log = { workspace = true }
lttb = "0.2.0"
maplit = "1.0.2"
map_gui = { path = "../../map_gui" }
map_model = { path = "../../map_model" }
petname = "1.1.3"
popdat = { path = "../../popdat" }
rand = { workspace = true }
rand_xorshift = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
svg_face = "0.1.3"
sim = { path = "../../sim" }
synthpop = { path = "../../synthpop" }
structopt = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
widgetry = { path = "../../widgetry" }
