[package]
name = "updater"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
flate2 = "1.0.20"
fs-err = { workspace = true }
futures-channel = { version = "0.3.12"}
md5 = "0.7.0"
structopt = { workspace = true }
tokio = { version = "1.19.2", features = ["full"] }
walkdir = "2.3.1"
