[package]
name = "convert_osm"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
geom = { path = "../geom" }
kml = { path = "../kml" }
log = "0.4.14"
map_model = { path = "../map_model" }
roxmltree = { version = "0.14.0", features=["std"] }
serde = "1.0.123"
