[package]
name = "kml"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
csv = "1.1.4"
geom = { path = "../geom" }
roxmltree = "0.13.0"
serde = "1.0.116"
