[package]
name = "geom"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
earcutr = { git = "https://github.com/dabreegster/earcutr", branch = "patch-1" }
geo = "0.13.0"
geo-booleanop = "0.3.0"
histogram = "0.6.9"
instant = "0.1.2"
ordered-float = { version = "1.0.1", features=["serde"] }
polylabel = "2.2.0"
serde = "1.0.110"
