[package]
name = "geom"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
earcutr = "0.1.1"
geo = { git = "https://github.com/Maximkaaa/geo", branch = "feature/k_nearest_concave_hull", features=["use-serde"] }
geo-booleanop = "= 0.3.2"
geojson = "0.22"
histogram = "0.6.9"
instant = "0.1.7"
ordered-float = { version = "2.0.0", features=["serde"] }
polylabel = "2.4"
serde = "1.0.123"
