[package]
name = "synthpop"
version = "0.1.0"
edition = "2021"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
geom = { workspace = true }
log = { workspace = true }
map_model = { path = "../map_model" }
rand = "0.8.5"
rand_xorshift = { workspace = true }
serde = { workspace = true, features=["derive"] }
