[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
bincode = "1.3.1"
env_logger = { version = "0.8.2" }
instant = "0.1.7"
itertools = "0.10.0"
log = "0.4.11"
num_cpus = "1.13.0"
scoped_threadpool = "0.1.9"
serde = "1.0.116"
serde_json = "1.0.61"

[target.'cfg(unix)'.dependencies]
termion = "1.5.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "0.2.0"
