[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
instant = "0.1.2"
num_cpus = "1.10.0"
rand = "0.7.0"
rand_xorshift = "0.2.0"
scoped_threadpool = "0.1.9"
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.4.7"

[target.'cfg(unix)'.dependencies]
termion = "1.5.1"
