[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.3.1"
env_logger = { version = "0.8.2" }
instant = "0.1.7"
itertools = "0.9.0"
lazy_static = "1.4.0"
log = { version = "0.4.11", features=["std"] }
num_cpus = "1.13.0"
scoped_threadpool = "0.1.9"
serde = "1.0.116"
serde_json = "1.0.57"

[target.'cfg(unix)'.dependencies]
termion = "1.5.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "0.2.0"
include_dir = { git = "https://github.com/dabreegster/include_dir", branch = "union" }
web-sys = { version = "0.3.4", features=["Storage", "Window"] }
