[package]
name = "blockfinding"
version = "0.1.0"
edition = "2021"

[dependencies]
abstutil = { path = "../abstutil" }
anyhow = { workspace = true }
geom = { workspace = true }
log = { workspace = true }
map_model = { path = "../map_model" }
serde = { workspace = true, features=["derive"] }
