[package]
name = "map_gui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2021"

[features]
native = ["built", "clipboard", "subprocess", "widgetry/native-backend"]
wasm = ["wasm-bindgen", "web-sys", "widgetry/wasm-backend"]
# A marker to use a named release from S3 instead of dev for updating files
release_s3 = []

[dependencies]
aabb-quadtree = "0.1.0"
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
built = { version = "0.5.0", optional = true, features=["chrono"] }
chrono = "0.4.15"
clipboard = { version = "0.5.0", optional = true }
colorous = "1.0.3"
contour = "0.4.0"
flate2 = "1.0.20"
futures-channel = { version = "0.3.12"}
geojson = { version = "0.22.2", features = ["geo-types"] }
geom = { path = "../geom" }
instant = "0.1.7"
lazy_static = "1.4.0"
log = "0.4.14"
lyon_geom = ">=0.16.2"
map_model = { path = "../map_model" }
regex = "1.5.4"
rfd = "0.8.0"
serde = "1.0.123"
sim = { path = "../sim" }
synthpop = { path = "../synthpop" }
structopt = "0.3.23"
subprocess = { git = "https://github.com/hniksic/rust-subprocess", optional = true }
wasm-bindgen = { version = "0.2.70", optional = true }
web-sys = { version = "0.3.47", optional = true }
widgetry = { path = "../widgetry" }
fs-err = "2.6.0"

[build-dependencies]
built = "0.5.0"
