[package]
name = "map_gui"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[features]
native = ["reqwest", "tokio"]
wasm = ["js-sys", "wasm-bindgen", "wasm-bindgen-futures", "web-sys"]
# A marker to use a named release from S3 instead of dev for updating files
release_s3 = []

[dependencies]
aabb-quadtree = "0.1.0"
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.38"
colorous = "1.0.3"
contour = "0.3.0"
flate2 = "1.0.20"
futures = { version = "0.3.12" }
futures-channel = { version = "0.3.12"}
geojson = "0.22"
geom = { path = "../geom" }
instant = "0.1.7"
js-sys = { version = "0.3.47", optional = true }
log = "0.4.14"
map_model = { path = "../map_model" }
reqwest = { version = "0.11.0", optional = true, default-features=false, features=["blocking", "rustls-tls"] }
serde = "1.0.123"
sim = { path = "../sim" }
tokio = { version ="1.1.1", features=["rt"], optional = true }
wasm-bindgen = { version = "0.2.70", optional = true }
wasm-bindgen-futures = { version = "0.4.20", optional = true }
webbrowser = "0.5.5"
widgetry = { path = "../widgetry" }

[dependencies.web-sys]
version = "0.3.47"
optional = true
features = [
  "Headers",
  "History",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
