[package]
name = "importer"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[features]
default = []
scenarios = ["gdal"]

[dependencies]
abstutil = { path = "../abstutil" }
convert_osm = { path = "../convert_osm" }
csv = "1.0.1"
geom = { path = "../geom" }
gdal = { version = "0.6.0", optional = true }
kml = { path = "../kml" }
map_model = { path = "../map_model" }
rand = "0.7.0"
rand_xorshift = "0.2.0"
serde = "1.0.110"
sim = { path = "../sim" }
